encoding: "utf-8"
excerpt_separator: "<!--more-->"
#permalink: date
#permalink: ordinal
permalink: "/archives/:year/:title.html"
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "/archives/page:num/"

name: "石頭閒語"
alias: "Rock Saying"
description: "遊手好閒的石頭成的部落格<br/>The Source Awakens! Make the source to be with you."
url: "www.rocksaying.tw"
repo_url: "https://github.com/rocksaying/rocksaying.github.io"

author:
  name: "遊手好閒的石頭成"
  description: "行於巷弄若於曠野，居於市井如於山巔。不知其何許人也。<br/><br/>我的程式源碼託管於 <a href='https://github.com/shirock/'>github</a>。"
  email: "shirock.tw@gmail.com"
  twitter: "tw_rocksaying"

cname:
  programming: "Programming"
  computer: "電腦技術"
  life: "休閒生活"
  reading: "閱讀隨筆"
  economics: "經濟學/奧地利經濟學派"
  events: "快報記事"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

kramdown:
  # GFM 允許 GitHub 式的 ``` code.
  input: GFM

sass:
  #sass_dir: _sass
  style: compressed
